for TIMESCALE in {1..20}
do
    python disc1.py --device 4 --target /mnt/ssd1/hiranotakaya/master/dev/workspace/prj_202409_2MR/laplace-version/train/output/0815/gesture/v1.1/dynasnn/dynasnn-tau_middle        --testnum 8 --droprate 0.3 --timescale ${TIMESCALE} --saveto output/0910/result/dynasnn-ts${TIMESCALE}
    python disc1.py --device 4 --target /mnt/ssd1/hiranotakaya/master/dev/workspace/prj_202409_2MR/laplace-version/train/output/0815/gesture/v1.1/dynasnn/dynasnn-tau_large         --testnum 8 --droprate 0.3 --timescale ${TIMESCALE} --saveto output/0910/result/dynasnn_large-ts${TIMESCALE}
    python disc1.py --device 4 --target /mnt/ssd1/hiranotakaya/master/dev/workspace/prj_202409_2MR/laplace-version/train/output/0815/gesture/v1.1/dynasnn/dynasnn-tau_small         --testnum 8 --droprate 0.3 --timescale ${TIMESCALE} --saveto output/0910/result/dynasnn_small-ts${TIMESCALE}
    python disc1.py --device 4 --target /mnt/ssd1/hiranotakaya/master/dev/workspace/prj_202409_2MR/laplace-version/train-multitime/output/0902/gesture/paramsnn/paramsnn-tau_middle --testnum 8 --droprate 0.3 --timescale ${TIMESCALE} --saveto output/0910/result/paramsnn-ts${TIMESCALE}
    python disc1.py --device 4 --target /mnt/ssd1/hiranotakaya/master/dev/workspace/prj_202409_2MR/laplace-version/train-multitime/output/0902/gesture/paramsnn/paramsnn-tau_large  --testnum 8 --droprate 0.3 --timescale ${TIMESCALE} --saveto output/0910/result/paramsnn_large-ts${TIMESCALE}
    python disc1.py --device 4 --target /mnt/ssd1/hiranotakaya/master/dev/workspace/prj_202409_2MR/laplace-version/train-multitime/output/0902/gesture/paramsnn/paramsnn-tau_small  --testnum 8 --droprate 0.3 --timescale ${TIMESCALE} --saveto output/0910/result/paramsnn_small-ts${TIMESCALE}
    python disc1.py --device 4 --target /mnt/ssd1/hiranotakaya/master/dev/workspace/prj_202409_2MR/laplace-version/train-multitime/output/0902/gesture/snn/snn-tau_large            --testnum 8 --droprate 0.3 --timescale ${TIMESCALE} --saveto output/0910/result/snn_large-ts${TIMESCALE}
    python disc1.py --device 4 --target /mnt/ssd1/hiranotakaya/master/dev/workspace/prj_202409_2MR/laplace-version/train-multitime/output/0902/gesture/snn/snn-tau_middle           --testnum 8 --droprate 0.3 --timescale ${TIMESCALE} --saveto output/0910/result/snn-ts${TIMESCALE}
    python disc1.py --device 4 --target /mnt/ssd1/hiranotakaya/master/dev/workspace/prj_202409_2MR/laplace-version/train-multitime/output/0902/gesture/snn/snn-tau_small            --testnum 8 --droprate 0.3 --timescale ${TIMESCALE} --saveto output/0910/result/snn_small-ts${TIMESCALE}
    python disc1.py --device 4 --target /mnt/ssd1/hiranotakaya/master/dev/workspace/prj_202409_2MR/laplace-version/train-multitime/output/0902/gesture/lstm                         --testnum 8 --droprate 0.3 --timescale ${TIMESCALE} --saveto output/0910/result/lstm-ts${TIMESCALE}
done