train:
  datapath: /mnt/ssd1/hiranotakaya/master/dev/workspace/prj_202409_2MR/laplace-version/train-data/xor_v2
  time_sequence: 100
  batch: 32
  epoch: 10
  iter: -1 #ここは-1にするとmaxまで
  lr: 0.001
  save_interval: 5 #epochごと
  datatype: dvsgesture

model:
  type: dynamic-snn

  in-size: 32
  in-channel: 2 
  out-size: 5
  hiddens: [1,4] 
  pool-type: max # IFEncは情報量がかなり落ちるのでmaxを使う
  pool-size: [4,4]
  residual-block: [2,2] #2にするとresidual blockあたり1+2層のCNNが積まれる
  is-bn: false #batch normalizationするかどうか. 
  clip-norm: 1.0 #勾配クリッピングの最大勾配. 一般的に1.0が使われる

  linear-hidden: 32

  dropout: 0.2


  dt: 0.001 #s
  init-tau: 0.02 #dt/tauが1を超えないようにする.
  min-tau: 0.001
  v-threshold: 0.03
  v-rest: 0.0
  reset-mechanism: zero
  spike-grad: fast-sigmoid
  output-membrane: true
  v-actf: tanh #膜電位vの活性化関数