train:
  datapath: /mnt/ssd1/hiranotakaya/master/dev/workspace/prj_202409_2MR/laplace-version/train-data/xor_v2
  time_sequence: 100
  batch: 32
  epoch: 10
  iter: -1 #ここは-1にするとmaxまで
  lr: 0.001
  save_interval: 5 #epochごと
  datatype: dvsgesture

model:
  type: dynamic-snn

  in-size: 4
  in-channel: 2 
  out-size: 4
  hiddens: [1,4]
  pool-type: avg
  pool-size: [2,2]
  is-bn: false #batch normalizationするかどうか
  clip-norm: 1.0

  linear-hidden: 4

  dropout: 0.2

  dt: 0.001 #s
  init-tau: 0.01 #dt/tauが1を超えないようにする.
  min-tau: 0.001
  v-threshold: 0.001
  v-rest: 0.0
  reset-mechanism: zero
  spike-grad: fast-sigmoid
  output-membrane: true